import {
  BadgeDollarSign,
  Boxes,
  Building2,
  CircleDollarSign,
  ClipboardList,
  Contact,
  CreditCard,
  DatabaseZap,
  FileChartColumn,
  FileClock,
  FileInput,
  HandCoins,
  LayoutDashboard,
  PackageCheck,
  PackageOpen,
  ReceiptText,
  RotateCcw,
  Scale,
  Shield,
  ShoppingCart,
  Store,
  Trash2,
  TrendingUp,
  UserCog,
  UsersRound,
  WalletCards,
  Warehouse,
  type LucideIcon,
} from "lucide-react";
import type { RouteAccess } from "./access";
import { resolvePathAccess } from "./access";

const access = (path: string): RouteAccess =>
  resolvePathAccess(path) ?? { resource: "REPORT", privilege: "VIEW" };

export interface AppRoute {
  path: string;
  title: string;
  description: string;
  group?: string;
  icon: LucideIcon;
  access: RouteAccess;
}

export const appRoutes: readonly AppRoute[] = [
  {
    path: "/",
    title: "Dashboard",
    description: "Business performance at a glance.",
    icon: LayoutDashboard,
    access: access("/"),
  },
  {
    path: "/purchase/purchases",
    title: "Purchases",
    description: "Manage purchase transactions.",
    group: "Purchase",
    icon: ShoppingCart,
    access: access("/purchase/purchases"),
  },
  {
    path: "/purchase/returns",
    title: "Purchase Returns",
    description: "Track returned purchases.",
    group: "Purchase",
    icon: RotateCcw,
    access: access("/purchase/returns"),
  },
  {
    path: "/purchase/vendors",
    title: "Vendors",
    description: "Manage vendor records.",
    group: "Purchase",
    icon: Building2,
    access: access("/purchase/vendors"),
  },
  {
    path: "/purchase/outstandings/payables",
    title: "Purchase Payables",
    description: "Amounts owed to vendors.",
    group: "Purchase",
    icon: CreditCard,
    access: access("/purchase/outstandings/payables"),
  },
  {
    path: "/purchase/outstandings/return-receivables",
    title: "Purchase-return Receivables",
    description: "Amounts due from purchase returns.",
    group: "Purchase",
    icon: HandCoins,
    access: access("/purchase/outstandings/return-receivables"),
  },
  {
    path: "/purchase/outstandings/rc-due",
    title: "Pending RCD",
    description: "RC Deposit amounts due from purchase vendors.",
    group: "Purchase",
    icon: HandCoins,
    access: access("/purchase/outstandings/rc-due"),
  },
  {
    path: "/sales/sales",
    title: "Sales",
    description: "Manage sales transactions.",
    group: "Sales",
    icon: BadgeDollarSign,
    access: access("/sales/sales"),
  },
  {
    path: "/sales/returns",
    title: "Sales Returns",
    description: "Track returned sales.",
    group: "Sales",
    icon: RotateCcw,
    access: access("/sales/returns"),
  },
  {
    path: "/sales/customers",
    title: "Customers",
    description: "Manage customer records.",
    group: "Sales",
    icon: Contact,
    access: access("/sales/customers"),
  },
  {
    path: "/sales/outstandings/receivables",
    title: "Sales Receivables",
    description: "Amounts due from customers and finance companies.",
    group: "Sales",
    icon: CircleDollarSign,
    access: access("/sales/outstandings/receivables"),
  },
  {
    path: "/sales/outstandings/return-payables",
    title: "Sale-return Payables",
    description: "Amounts owed for sales returns.",
    group: "Sales",
    icon: WalletCards,
    access: access("/sales/outstandings/return-payables"),
  },
  {
    path: "/inventory/stock",
    title: "Stock",
    description: "Review current inventory.",
    group: "Inventory",
    icon: Boxes,
    access: access("/inventory/stock"),
  },
  {
    path: "/inventory/sold",
    title: "Sold Inventory",
    description: "Review sold inventory.",
    group: "Inventory",
    icon: PackageCheck,
    access: access("/inventory/sold"),
  },
  {
    path: "/expenses/general",
    title: "General Expenses",
    description: "Track operating expenses.",
    group: "Expenses",
    icon: ReceiptText,
    access: access("/expenses/general"),
  },
  {
    path: "/expenses/purchase",
    title: "Purchase Expenses",
    description: "Track purchase-related expenses.",
    group: "Expenses",
    icon: ClipboardList,
    access: access("/expenses/purchase"),
  },
  {
    path: "/accounting/accounts",
    title: "Accounts",
    description: "Manage the chart of accounts.",
    group: "Accounting",
    icon: Store,
    access: access("/accounting/accounts"),
  },
  {
    path: "/accounting/direct-entry",
    title: "Direct Entry",
    description: "Record direct accounting entries.",
    group: "Accounting",
    icon: FileInput,
    access: access("/accounting/direct-entry"),
  },
  {
    path: "/accounting/other-income",
    title: "Other Income",
    description: "Record other income entries.",
    group: "Accounting",
    icon: CircleDollarSign,
    access: access("/accounting/other-income"),
  },
  {
    path: "/accounting/journals",
    title: "Journals",
    description: "Review journal entries.",
    group: "Accounting",
    icon: FileClock,
    access: access("/accounting/journals"),
  },
  {
    path: "/accounting/general-ledger",
    title: "General Ledger",
    description: "Review posted ledger activity.",
    group: "Accounting",
    icon: DatabaseZap,
    access: access("/accounting/general-ledger"),
  },
  {
    path: "/accounting/balance-sheet",
    title: "Balance Sheet",
    description: "Review assets, liabilities and equity.",
    group: "Accounting",
    icon: Scale,
    access: access("/accounting/balance-sheet"),
  },
  {
    path: "/accounting/trial-balance",
    title: "Trial Balance",
    description: "Review account balances.",
    group: "Accounting",
    icon: FileChartColumn,
    access: access("/accounting/trial-balance"),
  },
  {
    path: "/accounting/profit-and-loss",
    title: "Monthly Report",
    description: "Review profit and loss.",
    group: "Accounting",
    icon: TrendingUp,
    access: access("/accounting/profit-and-loss"),
  },
  {
    path: "/accounting/journal-profit-and-loss",
    title: "P&L Report",
    description: "Review revenue and expenses from posted journals.",
    group: "Accounting",
    icon: FileChartColumn,
    access: access("/accounting/journal-profit-and-loss"),
  },
  {
    path: "/accounting/warehouse-comparison",
    title: "Warehouse Comparison",
    description: "Compare stock and sales by warehouse.",
    group: "Accounting",
    icon: Warehouse,
    access: access("/accounting/warehouse-comparison"),
  },
  {
    path: "/more/recycle-bin",
    title: "Recycle Bin",
    description: "Review deleted records and audit history.",
    group: "More",
    icon: Trash2,
    access: access("/more/recycle-bin"),
  },
  {
    path: "/more/staff",
    title: "Staff Management",
    description: "Manage staff access and records.",
    group: "More",
    icon: UsersRound,
    access: access("/more/staff"),
  },
  {
    path: "/more/roles",
    title: "Roles & Permissions",
    description: "Manage roles and privilege grants.",
    group: "More",
    icon: Shield,
    access: access("/more/roles"),
  },
  {
    path: "/more/accounts",
    title: "Account Management",
    description: "Manage application accounts.",
    group: "More",
    icon: UserCog,
    access: access("/more/accounts"),
  },
  {
    path: "/more/products",
    title: "Product Management",
    description: "Manage products and catalog data.",
    group: "More",
    icon: PackageOpen,
    access: access("/more/products"),
  },
  {
    path: "/more/warehouses",
    title: "Warehouses",
    description: "Manage inventory storage locations.",
    group: "More",
    icon: Warehouse,
    access: access("/more/warehouses"),
  },
  {
    path: "/more/clear-data",
    title: "Clear Data",
    description: "Safely remove business data.",
    group: "More",
    icon: DatabaseZap,
    access: access("/more/clear-data"),
  },
] as const;

export const routeGroups = [
  "Purchase",
  "Sales",
  "Inventory",
  "Expenses",
  "Accounting",
  "More",
] as const;

export const getRouteByPath = (pathname: string): AppRoute | undefined =>
  appRoutes.find((route) => route.path === pathname);
