import {
  BadgeDollarSign,
  Boxes,
  Building2,
  CircleDollarSign,
  ClipboardList,
  Contact,
  CreditCard,
  DatabaseZap,
  FileChartColumn,
  FileClock,
  FileInput,
  HandCoins,
  LayoutDashboard,
  PackageCheck,
  PackageOpen,
  ReceiptText,
  RotateCcw,
  Scale,
  ShoppingCart,
  Store,
  Trash2,
  TrendingUp,
  UserCog,
  UsersRound,
  WalletCards,
  type LucideIcon,
} from "lucide-react";

export interface AppRoute {
  path: string;
  title: string;
  description: string;
  group?: string;
  icon: LucideIcon;
  adminOnly?: boolean;
}

export const appRoutes: readonly AppRoute[] = [
  {
    path: "/",
    title: "Dashboard",
    description: "Business performance at a glance.",
    icon: LayoutDashboard,
  },
  {
    path: "/purchase/purchases",
    title: "Purchases",
    description: "Manage purchase transactions.",
    group: "Purchase",
    icon: ShoppingCart,
  },
  {
    path: "/purchase/returns",
    title: "Purchase Returns",
    description: "Track returned purchases.",
    group: "Purchase",
    icon: RotateCcw,
  },
  {
    path: "/purchase/vendors",
    title: "Vendors",
    description: "Manage vendor records.",
    group: "Purchase",
    icon: Building2,
  },
  {
    path: "/purchase/outstandings/payables",
    title: "Purchase Payables",
    description: "Amounts owed to vendors.",
    group: "Purchase",
    icon: CreditCard,
  },
  {
    path: "/purchase/outstandings/return-receivables",
    title: "Purchase-return Receivables",
    description: "Amounts due from purchase returns.",
    group: "Purchase",
    icon: HandCoins,
  },
  {
    path: "/sales/sales",
    title: "Sales",
    description: "Manage sales transactions.",
    group: "Sales",
    icon: BadgeDollarSign,
  },
  {
    path: "/sales/returns",
    title: "Sales Returns",
    description: "Track returned sales.",
    group: "Sales",
    icon: RotateCcw,
  },
  {
    path: "/sales/customers",
    title: "Customers",
    description: "Manage customer records.",
    group: "Sales",
    icon: Contact,
  },
  {
    path: "/sales/outstandings/receivables",
    title: "Sales Receivables",
    description: "Amounts due from customers.",
    group: "Sales",
    icon: CircleDollarSign,
  },
  {
    path: "/sales/outstandings/return-payables",
    title: "Sale-return Payables",
    description: "Amounts owed for sales returns.",
    group: "Sales",
    icon: WalletCards,
  },
  {
    path: "/inventory/stock",
    title: "Stock",
    description: "Review current inventory.",
    group: "Inventory",
    icon: Boxes,
  },
  {
    path: "/inventory/sold",
    title: "Sold Inventory",
    description: "Review sold inventory.",
    group: "Inventory",
    icon: PackageCheck,
  },
  {
    path: "/expenses/general",
    title: "General Expenses",
    description: "Track operating expenses.",
    group: "Expenses",
    icon: ReceiptText,
  },
  {
    path: "/expenses/purchase",
    title: "Purchase Expenses",
    description: "Track purchase-related expenses.",
    group: "Expenses",
    icon: ClipboardList,
  },
  {
    path: "/accounting/accounts",
    title: "Accounts",
    description: "Manage the chart of accounts.",
    group: "Accounting",
    icon: Store,
  },
  {
    path: "/accounting/direct-entry",
    title: "Direct Entry",
    description: "Record direct accounting entries.",
    group: "Accounting",
    icon: FileInput,
  },
  {
    path: "/accounting/journals",
    title: "Journals",
    description: "Review journal entries.",
    group: "Accounting",
    icon: FileClock,
  },
  {
    path: "/accounting/general-ledger",
    title: "General Ledger",
    description: "Review posted ledger activity.",
    group: "Accounting",
    icon: DatabaseZap,
  },
  {
    path: "/accounting/balance-sheet",
    title: "Balance Sheet",
    description: "Review assets, liabilities and equity.",
    group: "Accounting",
    icon: Scale,
  },
  {
    path: "/accounting/trial-balance",
    title: "Trial Balance",
    description: "Review account balances.",
    group: "Accounting",
    icon: FileChartColumn,
  },
  {
    path: "/accounting/profit-and-loss",
    title: "Monthly Report",
    description: "Review profit and loss.",
    group: "Accounting",
    icon: TrendingUp,
  },
  {
    path: "/accounting/journal-profit-and-loss",
    title: "P&L Report",
    description: "Review revenue and expenses from posted journals.",
    group: "Accounting",
    icon: FileChartColumn,
    adminOnly: true,
  },
  {
    path: "/more/recycle-bin",
    title: "Recycle Bin",
    description: "Review deleted records and audit history.",
    group: "More",
    icon: Trash2,
  },
  {
    path: "/more/staff",
    title: "Staff Management",
    description: "Manage staff access and records.",
    group: "More",
    icon: UsersRound,
    adminOnly: true,
  },
  {
    path: "/more/accounts",
    title: "Account Management",
    description: "Manage application accounts.",
    group: "More",
    icon: UserCog,
    adminOnly: true,
  },
  {
    path: "/more/products",
    title: "Product Management",
    description: "Manage products and catalog data.",
    group: "More",
    icon: PackageOpen,
    adminOnly: true,
  },
  {
    path: "/more/clear-data",
    title: "Clear Data",
    description: "Safely remove business data.",
    group: "More",
    icon: DatabaseZap,
    adminOnly: true,
  },
] as const;

export const routeGroups = [
  "Purchase",
  "Sales",
  "Inventory",
  "Expenses",
  "Accounting",
  "More",
] as const;

export const getRouteByPath = (pathname: string): AppRoute | undefined =>
  appRoutes.find((route) => route.path === pathname);
